services:
  mongo-db:
    container_name: despliegue-mongo
    image: mongo:5.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: example
    ports:
      - 27018:27017
    volumes:
      - ./database:/data/db
      - ./scripts-mongo/user.js:/docker-entrypoint-initdb.d/user.js:ro
    networks:
      - network-despliegue

  node:
    container_name: despliegue-node
    build:
      context: .
      dockerfile: Dockerfile-node
    restart: unless-stopped
    ports:
      - 3003:3003
    depends_on:
      - mongo-db
    networks:
      - network-despliegue

  nginx:
    container_name: despliegue-nginx
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - node
    networks:
      - network-despliegue

networks:
  network-despliegue: